from __future__ import annotations

import pathlib
import re
import shutil
import tkinter as tk
from tkinter import filedialog, messagebox, ttk
from dataclasses import dataclass


ROOT = pathlib.Path(__file__).resolve().parent
TEMPLATES_DIR = ROOT / "osal_templates"


@dataclass(frozen=True)
class PrefixForms:
    upper: str
    camel: str
    pascal: str
    snake: str


def _to_words(value: str) -> list[str]:
    cleaned = re.sub(r"[^A-Za-z0-9]+", "_", value.strip())
    cleaned = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", cleaned)
    return [w for w in cleaned.split("_") if w]


def build_prefix_forms(prefix: str) -> PrefixForms:
    words = _to_words(prefix)
    if not words:
        raise ValueError("Prefix cannot be empty.")

    lower_words = [w.lower() for w in words]
    upper = "_".join(w.upper() for w in words)
    pascal = "".join(w.capitalize() for w in lower_words)
    camel = lower_words[0] + "".join(w.capitalize() for w in lower_words[1:])
    snake = "_".join(lower_words)
    return PrefixForms(upper=upper, camel=camel, pascal=pascal, snake=snake)


def apply_prefix(content: str, forms: PrefixForms) -> str:
    mapping = {
        "SYS_PARAM_SRV": forms.upper,
        "SysParamSrv": forms.pascal,
        "sysParamSrv": forms.camel,
        "sys_param_srv": forms.snake,
    }
    for src, dst in mapping.items():
        content = content.replace(src, dst)
    return content


def apply_api_profile_to_freertos_c(content: str, selected_apis: set[str]) -> str:
    entries = {
        "queue": [".queueCreate", ".queueDelete", ".queueItemPut", ".queueItemPend", ".queueReset"],
        "lock": [".lockObjCreate", ".lockObjDelete", ".lock", ".unlock"],
        "thread": [".threadCreate", ".threadDelete", ".threadSuspend", ".threadResume", ".threadDelay", ".threadExit"],
        "time": [".timeMsGet"],
        "memory": [".memAlloc", ".memFree"],
    }

    for api_group, fields in entries.items():
        if api_group in selected_apis:
            continue
        for field in fields:
            pattern = rf"^([ \t]*{re.escape(field)}[ \t]*=)[^,]+,"
            replacement = r"\1 NULL,"
            content = re.sub(pattern, replacement, content, flags=re.MULTILINE)
    return content


def render_profile_header(forms: PrefixForms, selected_apis: set[str], port: str) -> str:
    upper = forms.upper
    guard = f"{upper}_OSAL_PROFILE_H_"

    flags = {
        "queue": "QUEUE",
        "lock": "LOCK",
        "thread": "THREAD",
        "time": "TIME",
        "memory": "MEMORY",
    }

    lines = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "/* Auto-generated by OSAL Code Generator. */",
        f"#define {upper}_OSAL_PORT_{port.upper()}    1",
        "",
    ]

    for key, name in flags.items():
        val = 1 if key in selected_apis else 0
        lines.append(f"#define {upper}_OSAL_USE_{name}    {val}")

    lines.extend(["", f"#endif /* {guard} */", ""])
    return "\n".join(lines)


class App(tk.Tk):
    def __init__(self) -> None:
        super().__init__()
        self.title("OSAL C Code Generator")
        self.geometry("820x620")
        self.minsize(780, 560)
        self.configure(bg="#101826")

        self.style = ttk.Style(self)
        self.style.theme_use("clam")
        self._configure_styles()

        self.prefix_var = tk.StringVar(value="sys_param_srv")
        self.dest_var = tk.StringVar(value=str(ROOT / "generated"))
        self.port_var = tk.StringVar(value="freertos")

        self.api_vars = {
            "queue": tk.BooleanVar(value=True),
            "lock": tk.BooleanVar(value=True),
            "thread": tk.BooleanVar(value=True),
            "time": tk.BooleanVar(value=True),
            "memory": tk.BooleanVar(value=True),
        }

        self._build_ui()

    def _configure_styles(self) -> None:
        self.style.configure("Card.TFrame", background="#182235")
        self.style.configure("Title.TLabel", background="#182235", foreground="#f3f6ff", font=("Segoe UI", 15, "bold"))
        self.style.configure("Hint.TLabel", background="#182235", foreground="#b6c4dc", font=("Segoe UI", 10))
        self.style.configure("Body.TLabel", background="#182235", foreground="#e7eeff", font=("Segoe UI", 11))
        self.style.configure("Primary.TButton", font=("Segoe UI", 10, "bold"), padding=8)
        self.style.configure("TCheckbutton", background="#182235", foreground="#e7eeff", font=("Segoe UI", 10))

    def _build_ui(self) -> None:
        outer = ttk.Frame(self, style="Card.TFrame", padding=20)
        outer.pack(fill="both", expand=True, padx=20, pady=20)

        ttk.Label(outer, text="OSAL Generator for Embedded Projects", style="Title.TLabel").pack(anchor="w")
        ttk.Label(
            outer,
            text="Generate C source/header files from templates with custom prefix and API profile.",
            style="Hint.TLabel",
        ).pack(anchor="w", pady=(4, 20))

        form = ttk.Frame(outer, style="Card.TFrame")
        form.pack(fill="x")

        ttk.Label(form, text="Module Prefix", style="Body.TLabel").grid(row=0, column=0, sticky="w", pady=(0, 8))
        prefix_entry = ttk.Entry(form, textvariable=self.prefix_var, width=40)
        prefix_entry.grid(row=0, column=1, sticky="ew", padx=(10, 0), pady=(0, 8))

        ttk.Label(form, text="Port", style="Body.TLabel").grid(row=1, column=0, sticky="w", pady=(0, 8))
        port_combo = ttk.Combobox(form, textvariable=self.port_var, values=["freertos", "posix (coming soon)"], state="readonly", width=38)
        port_combo.grid(row=1, column=1, sticky="ew", padx=(10, 0), pady=(0, 8))

        ttk.Label(form, text="Output Folder", style="Body.TLabel").grid(row=2, column=0, sticky="w")
        path_frame = ttk.Frame(form, style="Card.TFrame")
        path_frame.grid(row=2, column=1, sticky="ew", padx=(10, 0))
        ttk.Entry(path_frame, textvariable=self.dest_var).pack(side="left", fill="x", expand=True)
        ttk.Button(path_frame, text="Browse", command=self._select_destination).pack(side="left", padx=(8, 0))

        form.columnconfigure(1, weight=1)

        api_card = ttk.Frame(outer, style="Card.TFrame", padding=(0, 18, 0, 8))
        api_card.pack(fill="x")
        ttk.Label(api_card, text="API Set", style="Body.TLabel").pack(anchor="w")

        checks = ttk.Frame(api_card, style="Card.TFrame")
        checks.pack(anchor="w", pady=(8, 0))
        labels = {
            "queue": "Queues",
            "lock": "Locks",
            "thread": "Threads",
            "time": "Time",
            "memory": "Memory",
        }
        for idx, key in enumerate(labels):
            ttk.Checkbutton(checks, text=labels[key], variable=self.api_vars[key]).grid(row=0, column=idx, padx=(0, 12), sticky="w")

        tips = (
            "• Choose FreeRTOS now. POSIX option is visible for future extension.\n"
            "• Disable APIs you don't need (e.g., only locks).\n"
            "• The tool rewrites module prefix in symbols and file names."
        )
        ttk.Label(outer, text=tips, style="Hint.TLabel", justify="left").pack(anchor="w", pady=(12, 20))

        actions = ttk.Frame(outer, style="Card.TFrame")
        actions.pack(fill="x")
        ttk.Button(actions, text="Generate", style="Primary.TButton", command=self.generate).pack(side="left")
        ttk.Button(actions, text="Open Output Folder", command=self._open_output).pack(side="left", padx=(10, 0))

        self.log = tk.Text(outer, height=12, bg="#0d1422", fg="#d9e5ff", insertbackground="#d9e5ff", relief="flat")
        self.log.pack(fill="both", expand=True, pady=(20, 0))
        self._log("Ready. Configure options and click Generate.")

    def _log(self, text: str) -> None:
        self.log.insert("end", text + "\n")
        self.log.see("end")

    def _select_destination(self) -> None:
        folder = filedialog.askdirectory(initialdir=self.dest_var.get() or str(ROOT))
        if folder:
            self.dest_var.set(folder)

    def _open_output(self) -> None:
        output = pathlib.Path(self.dest_var.get())
        if not output.exists():
            messagebox.showinfo("Info", "Output folder does not exist yet.")
            return
        try:
            if hasattr(pathlib, "WindowsPath"):
                import os
                os.startfile(str(output))  # type: ignore[attr-defined]
        except Exception:
            messagebox.showinfo("Info", f"Output: {output}")

    def generate(self) -> None:
        prefix_raw = self.prefix_var.get().strip()
        port_raw = self.port_var.get().strip().lower()
        output_root = pathlib.Path(self.dest_var.get().strip())

        selected = {name for name, var in self.api_vars.items() if var.get()}
        if not selected:
            messagebox.showerror("Error", "Select at least one API group.")
            return

        if port_raw != "freertos":
            messagebox.showerror("Error", "Currently only FreeRTOS port generation is implemented.")
            return

        try:
            forms = build_prefix_forms(prefix_raw)
        except ValueError as exc:
            messagebox.showerror("Error", str(exc))
            return

        if not TEMPLATES_DIR.exists():
            messagebox.showerror("Error", f"Templates directory not found: {TEMPLATES_DIR}")
            return

        try:
            module_dir = output_root / forms.snake
            portable_dir = module_dir / "portable"
            portable_dir.mkdir(parents=True, exist_ok=True)

            files = [
                TEMPLATES_DIR / "sys_param_srv_osal.h",
                TEMPLATES_DIR / "sys_param_srv_osal.c",
                TEMPLATES_DIR / "portable" / "sys_param_srv_osal_freertos.h",
                TEMPLATES_DIR / "portable" / "sys_param_srv_osal_freertos.c",
            ]

            for src in files:
                rel = src.relative_to(TEMPLATES_DIR)
                text = src.read_text(encoding="utf-8")
                text = apply_prefix(text, forms)
                if src.name.endswith("_freertos.c"):
                    text = apply_api_profile_to_freertos_c(text, selected)

                dst_rel = str(rel).replace("sys_param_srv", forms.snake)
                dst = module_dir / dst_rel
                dst.parent.mkdir(parents=True, exist_ok=True)
                dst.write_text(text, encoding="utf-8")
                self._log(f"Generated: {dst}")

            profile_name = f"{forms.snake}_osal_profile.h"
            profile_path = module_dir / profile_name
            profile_path.write_text(render_profile_header(forms, selected, port="freertos"), encoding="utf-8")
            self._log(f"Generated: {profile_path}")

            shutil.copy2(ROOT / "README.md", output_root / "README_generator.md") if (ROOT / "README.md").exists() else None

        except Exception as exc:
            messagebox.showerror("Generation failed", str(exc))
            self._log(f"ERROR: {exc}")
            return

        messagebox.showinfo("Success", f"Code generated into: {output_root}")
        self._log("Done.")


if __name__ == "__main__":
    App().mainloop()
