"""Text transformation helpers for the current OSAL template set."""

from __future__ import annotations

import re
from collections.abc import Iterable

from .model import GenerationConfig, PrefixForms
from .paths import port_slug


def apply_prefix(content: str, forms: PrefixForms) -> str:
    """Replace generic template prefixes in every naming convention in use."""
    mapping = {
        "TEMPLATE": forms.upper,
        "Template": forms.pascal,
        "template": forms.snake,
    }
    for source, destination in mapping.items():
        content = content.replace(source, destination)

    camel_symbol_prefix_pattern = re.compile(
        rf"\b{re.escape(forms.snake)}_osal(?=[A-Z])"
    )
    return camel_symbol_prefix_pattern.sub(f"{forms.camel}_osal", content)


def apply_api_profile_markers(
    content: str,
    selected_apis: set[str] | frozenset[str],
) -> str:
    """Keep enabled template sections and remove disabled API groups."""
    marker_to_api = {
        "QUEUE": "queue",
        "STREAM_BUFFER": "stream_buffer",
        "MUTEX": "mutex",
        "SEMAPHORE": "semaphore",
        "EVENT_FLAGS": "event_flags",
        "THREAD": "thread",
        "CRITICAL_SECTION": "critical_section",
        "SOFTWARE_TIMER": "software_timer",
        "TIME": "time",
        "MEMORY": "memory",
    }

    for marker, api_name in marker_to_api.items():
        pattern = re.compile(
            rf"(?ms)^[ \t]*//[ \t]*BEGIN[ \t]+{marker}[ \t]*\n"
            rf"(.*?)"
            rf"^[ \t]*//[ \t]*END[ \t]+{marker}[ \t]*\n?"
        )
        if api_name in selected_apis:
            content = pattern.sub(r"\1", content)
        else:
            content = pattern.sub("", content)

    return content


def render_profile_header(
    forms: PrefixForms,
    selected_apis: frozenset[str],
    ports: Iterable[str],
) -> str:
    """Render the generated C profile header for the selected OSAL API set."""
    upper = forms.upper
    guard = f"{upper}_OSAL_PROFILE_H_"

    flags = {
        "queue": "QUEUE",
        "stream_buffer": "STREAM_BUFFER",
        "mutex": "MUTEX",
        "semaphore": "SEMAPHORE",
        "event_flags": "EVENT_FLAGS",
        "thread": "THREAD",
        "critical_section": "CRITICAL_SECTION",
        "software_timer": "SOFTWARE_TIMER",
        "time": "TIME",
        "memory": "MEMORY",
    }

    lines = [
        "/*",
        " * SPDX-License-Identifier: MIT",
        " * Copyright (c) 2026 Kiwi contributors",
        " */",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "/* Auto-generated by kiwicgen. */",
    ]

    for port in ports:
        port_macro = re.sub(r"[^A-Za-z0-9]+", "_", port).upper().strip("_")
        lines.append(f"#define {upper}_OSAL_PORT_{port_macro}    1")

    lines.append("")

    for key, name in flags.items():
        value = 1 if key in selected_apis else 0
        lines.append(f"#define {upper}_OSAL_USE_{name}    {value}")

    lines.extend(["", f"#endif /* {guard} */", ""])
    return "\n".join(lines)


def render_base_cmake(forms: PrefixForms, config: GenerationConfig) -> str:
    """Render the generic OSAL CMake file when layout rewriting is required."""
    source = (
        f"src/{forms.snake}_osal.c"
        if config.split_src_inc_files
        else f"{forms.snake}_osal.c"
    )
    include_dir = (
        "${CMAKE_CURRENT_LIST_DIR}/include"
        if config.split_src_inc_files
        else "${CMAKE_CURRENT_LIST_DIR}"
    )
    return "\n".join(
        [
            "# SPDX-License-Identifier: MIT",
            "# Copyright (c) 2026 Kiwi contributors",
            "",
            "# Base OSAL generated build script.",
            "",
            f"add_library({forms.snake}_osal STATIC",
            f"    {source}",
            ")",
            "",
            f"target_include_directories({forms.snake}_osal",
            "    PUBLIC",
            f"        {include_dir}",
            ")",
            "",
        ]
    )


def render_port_cmake(
    forms: PrefixForms,
    config: GenerationConfig,
    port: str,
) -> str:
    """Render one backend CMake file for split output layouts."""
    slug = port_slug(port)
    source = (
        f"src/{forms.snake}_osal_{slug}.c"
        if config.split_src_inc_files
        else f"{forms.snake}_osal_{slug}.c"
    )
    port_include = (
        "${CMAKE_CURRENT_LIST_DIR}/include"
        if config.split_src_inc_files
        else "${CMAKE_CURRENT_LIST_DIR}"
    )
    base_include = (
        "${CMAKE_CURRENT_LIST_DIR}/../../include"
        if config.split_src_inc_files
        else "${CMAKE_CURRENT_LIST_DIR}/../.."
    )
    lines = [
        "# SPDX-License-Identifier: MIT",
        "# Copyright (c) 2026 Kiwi contributors",
        "",
        f"# {port} OSAL port generated build script.",
        f"# {port} include paths and libraries are expected from the parent project.",
        "",
    ]

    if port == "POSIX":
        lines.extend(["find_package(Threads REQUIRED)", ""])

    lines.extend(
        [
            f"add_library({forms.snake}_osal_{slug} STATIC",
            f"    {source}",
            ")",
            "",
            f"target_include_directories({forms.snake}_osal_{slug}",
            "    PUBLIC",
            f"        {port_include}",
            f"        {base_include}",
            ")",
            "",
        ]
    )

    if port == "POSIX":
        lines.extend(
            [
                f"target_compile_features({forms.snake}_osal_{slug} PUBLIC c_std_99)",
                "",
                f"target_compile_definitions({forms.snake}_osal_{slug}",
                "    PUBLIC",
                "        _POSIX_C_SOURCE=200809L",
                ")",
                "",
            ]
        )

    link_libraries = [forms.snake + "_osal"]
    if port == "POSIX":
        link_libraries.append("Threads::Threads")

    lines.extend(
        [
            f"target_link_libraries({forms.snake}_osal_{slug}",
            "    PUBLIC",
            *[f"        {library}" for library in link_libraries],
            ")",
            "",
        ]
    )

    return "\n".join(lines)


def render_combined_cmake(forms: PrefixForms, config: GenerationConfig) -> str:
    """Render one CMake file when generic and backend files share a module root."""
    base_source = (
        f"src/{forms.snake}_osal.c"
        if config.split_src_inc_files
        else f"{forms.snake}_osal.c"
    )
    include_dir = (
        "${CMAKE_CURRENT_LIST_DIR}/include"
        if config.split_src_inc_files
        else "${CMAKE_CURRENT_LIST_DIR}"
    )
    lines = [
        "# SPDX-License-Identifier: MIT",
        "# Copyright (c) 2026 Kiwi contributors",
        "",
        "# Combined base + selected OSAL ports generated build script.",
        "# Native OS include paths and libraries are expected from the parent project.",
        "",
    ]

    if "POSIX" in config.ports:
        lines.extend(["find_package(Threads REQUIRED)", ""])

    lines.extend(
        [
            f"add_library({forms.snake}_osal STATIC",
            f"    {base_source}",
            ")",
            "",
            f"target_include_directories({forms.snake}_osal",
            "    PUBLIC",
            f"        {include_dir}",
            ")",
            "",
        ]
    )

    for port in config.ports:
        slug = port_slug(port)
        port_source = (
            f"src/{forms.snake}_osal_{slug}.c"
            if config.split_src_inc_files
            else f"{forms.snake}_osal_{slug}.c"
        )
        lines.extend(
            [
                f"add_library({forms.snake}_osal_{slug} STATIC",
                f"    {port_source}",
                ")",
                "",
                f"target_include_directories({forms.snake}_osal_{slug}",
                "    PUBLIC",
                f"        {include_dir}",
                ")",
                "",
            ]
        )

        if port == "POSIX":
            lines.extend(
                [
                    f"target_compile_features({forms.snake}_osal_{slug} PUBLIC c_std_99)",
                    "",
                    f"target_compile_definitions({forms.snake}_osal_{slug}",
                    "    PUBLIC",
                    "        _POSIX_C_SOURCE=200809L",
                    ")",
                    "",
                ]
            )

        link_libraries = [forms.snake + "_osal"]
        if port == "POSIX":
            link_libraries.append("Threads::Threads")

        lines.extend(
            [
                f"target_link_libraries({forms.snake}_osal_{slug}",
                "    PUBLIC",
                *[f"        {library}" for library in link_libraries],
                ")",
                "",
            ]
        )

    return "\n".join(lines)
